title: CocoaHeads Australia and New Zealand

params:
  author: CocoaHeads Australia and New Zealand
  description: Find your nearest CocoaHeads community
  color: C0810B

  socials:
    slack: https://join.slack.com/t/cocoaheads-aunz/shared_invite/zt-2140qdy39-MI5mXIHJo7Nz_mHEEVd6rg
